title:             JINH-ZERO-PARK
email:             jinh0park@naver.com
description:       jinh0park's Personal Place
author:            jinh0park
baseurl:           ""
url:               "http://jinh0park.github.io"


# Social Profiles
#twitter_username:  SBootstrap
github_username:   jinh0park
facebook_username: jinh0park

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
